---
jira:
  # url: https://issues.redhat.com
  project-id: EC
comments:
  footer: >
    {color:#505f79}See also
    [ec.yaml|https://github.com/konflux-ci/prioritize/blob/main/config/ec.yaml],
    the [source code|https://github.com/konflux-ci/prioritize], and the
    [runner|https://gitlab.cee.redhat.com/rbean/jira-automation/-/blob/main/.gitlab-ci.yml]
    for this bot.{color}
team_automation:
  issues:
    Epic:
      # collector: get_issues
      rules: []
      group_rules:
        - check_rank
    Story:
      # collector: get_issues
      # Todo: Consider using the filter used by the scrum board,
      # https://issues.redhat.com/issues/?filter=12422356
      rules: []
      group_rules:
        - check_rank
