---
jira:
  # url: https://issues.redhat.com
  project-id: KONFLUX
  subquery: filter!=12422371
program_automation:
  issues:
    Feature:
      # collector: get_issues
      rules:
        - check_target_end_date
    Outcome:
      # collector: get_issues
      rules:
        - check_components
        - check_target_end_date
team_automation:
  issues:
    Feature:
      # collector: get_issues
      group_rules:
        - check_timesensitive_rank
    Epic:
      collector: get_child_issues
      rules:
        - rule: check_due_date
          kwargs:
            ignore:
              - SVPI-730
              - STONEINTG-767
              - STONEBLD-2116
              - RHTAPWATCH-743
              - RHTAPSRE-366
              - RHTAPREL-809
              - PLNSRVCE-1605
              - HAC-5626
              - GITOPSRVCE-800
              - EC-367
              - DEVHAS-606
              - ASC-454
              - PSSECAUT-362
